name: Deploy Streamlit App with VPN

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up VPN
      run: |
        echo "${{ secrets.VPN_CONFIG }}" > vpnconfig.ovpn
        sudo apt-get update
        sudo apt-get install -y openvpn

    - name: Disable needrestart
      run: |
        echo 'NEEDRESTART_MODE=a' | sudo tee /etc/needrestart/needrestart.conf > /dev/null

    - name: Start VPN
      run: |
        sudo openvpn --config vpnconfig.ovpn --log /tmp/openvpn.log --daemon
        sleep 10  # Give the VPN time to connect
        sudo chmod 644 /tmp/openvpn.log  # Adjust permissions to read the log file

    - name: Check VPN connection
      run: |
        curl -s https://ipinfo.io  # Verify the IP address to ensure VPN is connected

    - name: Output OpenVPN log
      run: |
        cat /tmp/openvpn.log  # Output the log to check for any errors

    - name: Deploy Streamlit app
      run: |
        streamlit run app.py
